version: '3'

services:
  webserver:
    image: httpd:latest
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    ports:
      - "8186:80"
      
  frontend:
    build:
      context: .
    volumes:
      - ./html:/app/build
    ports:
      - "3004:3000"  # Browsersync Local
      - "3003:3001"  # Browsersync UI
